from __future__ import annotations

from .prompt_templates import (
    ANSWER_EVALUATION_PROMPT,
    FINAL_ANSWER_PROMPT,
    EXTRACTION_PROMPT,
    QUESTION_DECOMPOSITION_PROMPT,
    SINGLE_QUESTION_ANSWER_PROMPT,
)

__all__ = (
    "ANSWER_EVALUATION_PROMPT",
    "FINAL_ANSWER_PROMPT",
    "EXTRACTION_PROMPT",
    "QUESTION_DECOMPOSITION_PROMPT",
    "SINGLE_QUESTION_ANSWER_PROMPT",
)
